### ISSUE TITLE
"foobar" and "foo1bar"

### ISSUE THREAD

**Issue by khushijain21** [fvbommel/sortorder#6]
When you run chk := sortorder.NaturalLess("foobar", "foo1bar") - it returns false?

In this case foobar is smaller than foo1bar right and should return true instead

**Comment by fvbommel** [comment]
You didn't explain your reasoning, but think of it like this: `NaturalLess` splits the inputs up into numbers and non-digit strings, and then compares numbers numerically and non-digits as strings, starting from the beginning. (That's not the full algorithm due to cases like `"2"` vs `"02"` which are different strings that are numerically equal, but close enough for this explanation)

In this case, you're comparing `["foobar"]` to `["foo", 1, "bar"]` and when it compares those initial strings it gets `"foo"` < `"foobar"`, so `"foo1bar"` < `"foobar"`
